# Generated by Django 2.1.2 on 2018-10-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoloc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='score',
            field=models.FloatField(default=1.0),
        ),
    ]
